<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="csrf-token" content="{{ csrf_token() }}" />
    <title>Qr code</title>

    <link href="/backend/vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="/backend/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
  
    <!-- Custom Theme Style -->
    <link href="/backend/build/css/custom.min.css" rel="stylesheet">
    <!-- Datatables -->
    <link rel="stylesheet" href="/backend/vendors/datatables.net-bs/css/dataTables.bootstrap.min.css">
    <link rel="stylesheet" href="/backend/vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css">
    @yield('style')
</head>
<body>
<!-- qr code  -->
<div class=" text-center">
    {{-- @if(Auth::user()->id) --}}
      <img src="data:image/png;base64, {!! base64_encode(QrCode::format('png')->color(38, 38, 38, 0.85)->backgroundColor(255, 255, 255, 0.82)->size(200)->generate(Auth::user()->barcode)) !!} ">
      <p> This is your qr code , Download it into your mobile</p>
      {{-- {!! QrCode::generate(); !!} --}}
      {{-- @endif --}}
      
  <button type="submit" id="autogenerate_qr" class="btn btn-default sub6">Change Now</button>
    </div>
    
    {{-- {!! QrCode::generate('Make me into a QrCode!'); !!} --}}
    
   

<script src="/backend/vendors/jquery/dist/jquery.min.js"></script>
<!-- Bootstrap -->
<script src="/backend/vendors/bootstrap/dist/js/bootstrap.min.js"></script>
<!-- FastClick -->
<script src="/backend/vendors/fastclick/lib/fastclick.js"></script>
<!-- NProgress -->
<script src="/backend/vendors/nprogress/nprogress.js"></script>

<!-- Custom Theme Scripts -->
<script src="/backend/build/js/custom.min.js "></script>
<!-- datatables -->
<script src="/backend/vendors/datatables.net/js/jquery.dataTables.min.js"></script>
<script src="/backend/vendors/datatables.net-responsive/js/dataTables.responsive.min.js"></script>

<script type="text/javascript">
  $.ajaxSetup({
      headers: {
        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
      }
    });
</script>

<script>
    //Delete Items
    $('#autogenerate_qr').click(function(){
   if(confirm('Are you sure you want to generate the qe code')){

      $.ajax({
         type: "POST",
         cache: false,
         url : "/ambilqrcode",
         data: {action:'updateqr'},
             success: function(data) {
               if (data==1) {
                location.reload();
              }else{
               alert( 'Ups error :P ');
              }
             }
         })

   
 }else{
     return false;
 }
});
   //end qr autogenerated
 </script>

@yield('scripts')
</body>
</html>